name: PHP Static Analysis
on:
  workflow_call:
    inputs:
      version:
        type: string
        default: "^1.8"
      paths:
        type: string
        default: "src"
      autoload-file:
        type: string
        default: "vendor/autoload.php"

permissions:
  contents: read

jobs:
    static_analysis:
      runs-on: ubuntu-latest
      name: PHPStan Static Analysis
      steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Run Script
        run: |
          composer install -q
          composer global require phpstan/phpstan:${INPUTS_VERSION} -q
          ~/.composer/vendor/bin/phpstan analyse ${INPUTS_PATHS} \
            --autoload-file=${INPUTS_AUTOLOAD_FILE}
        env:
          INPUTS_VERSION: ${{ inputs.version }}
          INPUTS_PATHS: ${{ inputs.paths }}
          INPUTS_AUTOLOAD_FILE: ${{ inputs.autoload-file }}
